# **Business Understanding**

A simple yet challenging project, to predict the housing price based on certain factors like house area, bedrooms, furnished, nearness to mainroad, etc. The dataset is small yet, it's complexity arises due to the fact that it has strong multicollinearity. Can you overcome these obstacles & build a decent predictive model?


*Objective:*
Run a predition using a linear regression model.

*Acknowledgement:*
Harrison, D. and Rubinfeld, D.L. (1978) Hedonic prices and the demand for clean air. J. Environ. Economics and Management 5, 81–102.

Belsley D.A., Kuh, E. and Welsch, R.E. (1980) Regression Diagnostics. Identifying Influential Data and Sources of Collinearity. New York: Wiley.



*Source*: [Housing Data](https://www.kaggle.com/datasets/yasserh/housing-prices-dataset)

#### **Loading Libraries**

In [1]:
import pandas as pd # data manipulation and reading the dat as a dataframe
from sklearn.linear_model import LinearRegression # we use sklearn as it composes many ML algorithms that we can use
from sklearn.model_selection import train_test_split # we split the data to use it well

#### **Loading data**

In [2]:
df = pd.read_csv("data/Housing.csv")

# **Data Understaning**

##### **Snippet of the data**

In [3]:
df.head()

      price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

##### **Shape of data**

In [4]:
rows, columns = df.shape
output = f" Housing data is composed of {rows} records and {columns} features"
print(output)

 Housing data is composed of 545 records and 13 features

##### **Get general info**

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

##### **statistical summary**

In [ ]:
df.describe() # this captures the numerical columns

              price          area  ...     stories     parking
count  5.450000e+02    545.000000  ...  545.000000  545.000000
mean   4.766729e+06   5150.541284  ...    1.805505    0.693578
std    1.870440e+06   2170.141023  ...    0.867492    0.861586
min    1.750000e+06   1650.000000  ...    1.000000    0.000000
25%    3.430000e+06   3600.000000  ...    1.000000    0.000000
50%    4.340000e+06   4600.000000  ...    2.000000    0.000000
75%    5.740000e+06   6360.000000  ...    2.000000    1.000000
max    1.330000e+07  16200.000000  ...    4.000000    3.000000

[8 rows x 6 columns]

In [7]:
df.describe(include="object") # this captures the non-numerical columns

/tmp/ipykernel_5813/243942468.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object") # this captures the non-numerical columns

       mainroad guestroom basement  ... airconditioning prefarea furnishingstatus
count       545       545      545  ...             545      545              545
unique        2         2        2  ...               2        2                3
top         yes        no       no  ...              no       no   semi-furnished
freq        468       448      354  ...             373      417              227

[4 rows x 7 columns]

# **Data Preparation**

# **Modeling**

In [ ]:
regressor = LinearRegression()
regressor

# **Evaluation**

# **Deployment**